/// Emits payloads encrypted by the Dart implementation so the Node test suite
/// can prove it reads them. Together with test/fixtures/crypto_vectors.json
/// this closes both directions of the interop contract.
///
/// Run from desktop_app/:  dart run tool/emit_dart_vectors.dart
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:vault_desktop/data/vault_crypto.dart';

Uint8List hexToBytes(String hex) {
  return Uint8List.fromList([
    for (var i = 0; i < hex.length; i += 2)
      int.parse(hex.substring(i, i + 2), radix: 16),
  ]);
}

void main() {
  const master = 'a-strong-master-password';
  final salt = hexToBytes('0123456789abcdef0123456789abcdef');
  final key = VaultCrypto.deriveKey(master, salt);

  const plaintexts = [
    '',
    's3cret',
    'admin@example.dev',
    'https://acme.dev/admin',
    'línea uno\nlínea dos — ñ ü 🔐',
    '  leading and trailing spaces  ',
    'true',
    'default',
  ];

  final output = {
    'note':
        'Generated by desktop_app/tool/emit_dart_vectors.dart — do not edit by hand.',
    'password': master,
    'saltHex': '0123456789abcdef0123456789abcdef',
    'derivedKeyHex': key
        .map((b) => b.toRadixString(16).padLeft(2, '0'))
        .join(),
    'verifierBase64': VaultCrypto.createVerifier(key),
    'vectors': [
      for (final plaintext in plaintexts)
        {
          'plaintext': plaintext,
          'payloadBase64': VaultCrypto.encrypt(plaintext, key),
        },
    ],
  };

  final file = File('../src/lib/fixtures/dart_vectors.json');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(output)}\n');

  stdout.writeln('wrote ${plaintexts.length} Dart-encrypted vectors to ${file.path}');
}
