/**
 * Emits cross-language test vectors produced by the Node implementation.
 * The Dart tests read this file and must reproduce every value exactly —
 * that is the only thing keeping the two crypto implementations in step.
 *
 * Run from the repo root:  node desktop_app/tool/generate_fixtures.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  CURRENT_KDF_VERSION,
  createSalt,
  createVerifier,
  deriveKey,
  encrypt,
} from "../../src/lib/crypto.ts";

/** Every version the parameter table defines. Keep in step with crypto.ts. */
const KDF_VERSIONS = [1, 2] as const;

const here = path.dirname(fileURLToPath(import.meta.url));
const outputDir = path.join(here, "..", "test", "fixtures");

const MASTER = "a-strong-master-password";

// Fixed salt so the derived key is a stable, checkable constant.
const salt = Buffer.from("0123456789abcdef0123456789abcdef", "hex");
const key = deriveKey(MASTER, salt);

const plaintexts = [
  "",
  "s3cret",
  "admin@example.dev",
  "https://acme.dev/admin",
  "línea uno\nlínea dos — ñ ü 🔐",
  "  leading and trailing spaces  ",
  "true",
  "default",
  "x".repeat(500),
];

/**
 * Passwords whose UTF-8 bytes differ from the bytes of their NFKC form.
 * `deriveKey` normalizes before hashing, so a client that skips normalization
 * derives a different key from the same typed password and cannot unlock a
 * vault the other client created. macOS produces decomposed accents in several
 * input paths, so this is reachable by simply typing "contraseña".
 */
const normalizationCases = [
  // Escape sequences, not literals: the exact code points are the whole point
  // of these cases, and a literal accent in this file could be saved either way.
  { label: "decomposed n-tilde", password: "contrasen\u0303a" },
  { label: "composed n-tilde", password: "contrase\u00f1a" },
  { label: "decomposed a-acute", password: "ma\u0301ster clave" },
  { label: "compatibility ligature", password: "o\ufb03ce vault" },
  { label: "full-width latin", password: "\uff56\uff41\uff55\uff4c\uff54" },
  { label: "plain ascii is unchanged", password: "plain-ascii" },
];

const fixtures = {
  note: "Generated by desktop_app/tool/generate_fixtures.ts — do not edit by hand.",
  scrypt: {
    password: MASTER,
    saltHex: salt.toString("hex"),
    kdfVersion: CURRENT_KDF_VERSION,
    keyLength: 32,
    expectedKeyHex: key.toString("hex"),
  },
  // A random salt proves derivation is not accidentally hardcoded.
  scryptSecondary: (() => {
    const otherSalt = createSalt();
    return {
      password: "another master password",
      saltHex: otherSalt.toString("hex"),
      expectedKeyHex: deriveKey("another master password", otherSalt).toString("hex"),
    };
  })(),
  verifier: {
    // Dart must accept this with the right key and reject it with a wrong one.
    payloadBase64: createVerifier(key),
    wrongKeyHex: deriveKey("not the master", salt).toString("hex"),
  },
  /**
   * One entry per row of the scrypt parameter table, so both clients are
   * pinned at every version rather than only at whichever one is current.
   * A version whose parameters drift on one side fails here instead of
   * quietly locking that side out of vaults the other wrote.
   */
  kdfVersions: KDF_VERSIONS.map((version) => ({
    version,
    password: MASTER,
    saltHex: salt.toString("hex"),
    expectedKeyHex: deriveKey(MASTER, salt, version).toString("hex"),
  })),
  vectors: plaintexts.map((plaintext) => ({
    plaintext,
    payloadBase64: encrypt(plaintext, key),
  })),
  normalization: normalizationCases.map(({ label, password }) => ({
    label,
    password,
    // The code points as typed, so a mangled fixture file is obvious on sight.
    codePoints: [...password].map((c) => c.codePointAt(0)!),
    saltHex: salt.toString("hex"),
    expectedKeyHex: deriveKey(password, salt).toString("hex"),
  })),
};

mkdirSync(outputDir, { recursive: true });
const outputPath = path.join(outputDir, "crypto_vectors.json");
writeFileSync(outputPath, JSON.stringify(fixtures, null, 2) + "\n");

console.log(`wrote ${fixtures.vectors.length} vectors to ${outputPath}`);
